### ISSUE TITLE
Display information in table?

### ISSUE THREAD

**Issue by greatest-ape** [HDVinnie/Torrent-Tracker-Platforms#16]
Hey,

I think it might be clearer to display tracker info in table format, e.g.,

[aquatic]: https://github.com/greatest-ape/aquatic
[opentracker]: http://erdgeist.org/arts/software/opentracker
[Radiance]: https://github.com/Empornium/Radiance

| Name        | Type    | UDP | HTTP | WebTorrent | TLS | IPv6 | Languages | OS support            |
|-------------|---------|-----|------|------------|-----|------|-----------|-----------------------|
| [aquatic]     | Open    | Yes | Yes  | Yes        | Yes | Yes  | Rust      | Unix-like / Linux 5.8 |
| [opentracker] | Open    | Yes | Yes  | No         | No  | Yes  | C         | Unix-like             |
| [Radiance]    | Private | Yes | Yes  | No         | No  | Yes  | C++       | Unix-like             |

Table markup can be generated with e.g. https://www.tablesgenerator.com/markdown_tables.

What do you think?

**Comment by HDVinnie** [comment]
Yeah looks good to me....been meaning too do tables. Feel free to make a PR and ill review and adjust/add to it as needed.

**Comment by greatest-ape** [comment]
@HDVinnie #17 :-)
