### ISSUE TITLE
Add GreatPosterWall (GPW) to the list

### ISSUE THREAD

**Issue by zotabee** [HDVinnie/Torrent-Tracker-Platforms#9]
https://github.com/TOMMMMMMMMMC/GreatPosterWall
https://github.com/TOMMMMMMMMMC/Ocelot

Source : https://www.reddit.com/r/trackers/comments/r2v9zm/gpw_opensourced_their_moviefocused_gazelle_fork/
Original request : https://www.reddit.com/r/trackers/comments/qfl5is/will_anthelion_or_gpw_ever_share_their_gazelle/

**Comment by HDVinnie** [comment]
Wouldn't its be better to wait for GreatPosterWall to release it officially on Git? Otherwise this is just a leaked dump that will get no updates and offer no support.

**Comment by zotabee** [comment]
Just learnt that, sorry. Yep I think it's not a great idea then.
